name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install sqlite
      run: sudo apt-get install -y libsqlite3-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests on main
      run: cargo test --verbose

  e2e:
    runs-on: ubuntu-latest
    env:
      REDIS_HOST: 127.0.0.1

    steps:
    - uses: actions/checkout@v3

    - id: setup
      uses: shogo82148/actions-setup-redis@v1

    - name: Install shunit
      run: sudo apt install -y shunit2 libsqlite3-dev redis-tools

    - name: I can connect with redis here
      run: redis-cli -h 127.0.0.1 -p 6379 ping

    - name: Test with shunit
      run: ./shunit.sh
